version: '3'
services:
  kaddem:
    image: bessembenammar-5sae3-skieur:latest
    restart: on-failure
    ports:
      - '8089:8089'
    depends_on:
      - mysql
    networks:
      - mynetwork
    volumes:
      - .m2:/root/.m2
  mysql:
    image: mysql:latest
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: bessem
      MYSQL_DATABASE: stationSki
      MYSQL_USER: bessem
      MYSQL_PASSWORD: bessem
    networks:
      - mynetwork
    volumes:
      - mysql-data:/var/lib/mysql
      
networks:
  mynetwork:
    driver: bridge

volumes:
  mysql-data:
  .m2:
